# must be unique in a given SonarQube Server instance
sonar.projectKey=Mitul-Angular-Secound-group

# --- optional properties ---

# defaults to project key
sonar.projectName=Mitul-Angular-Secound-group
defaults to 'not provided'
sonar.projectVersion=1.0
sonar.host.url=http://192.168.0.42:9000
sonar.token=squ_f51f6d63b325b148d75b2d8c384acf2153c80f38
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage\bus-booking-angular-18\lcov.info
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8