name: Build and deploy Angular app to Azure

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # Checkout code

      - uses: actions/checkout@v3

      # Setup Node

      - name: Setup Node

        uses: actions/setup-node@v3

        with:

          node-version: '18'

      # Clean + Install dependencies

      - name: Clean install dependencies

        run: |

          rm -rf node_modules package-lock.json

          npm cache clean --force

          npm install --legacy-peer-deps

      # Install Angular CLI

      - name: Install Angular CLI

        run: npm install -g @angular/cli

      # Build Angular app

      - name: Build Angular app

        run: npx ng build --configuration production

      # Deploy to Azure Web App

      - name: Deploy to Azure

        uses: azure/webapps-deploy@v2

        with:

          app-name: mitul-app

          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

          package: ./dist
          package: ./dist
